#!/usr/bin/env bash

set -xeu

# python static tool checkers
python -m brunette --check --diff --skip-string-normalization --config setup.cfg "."
python -m isort --check-only --diff --profile black "."
python -m prospector "." --no-autodetect

# bash static tool checkers
find "." -name "*.sh" -type f -not -path '*/\.venv/*' -not -path '*/\.tox/*' -exec shellcheck -x {} \;
