# the configuration of the tools can be found in this file and in pyproject.toml
strictness: veryhigh
test-warnings: true
doc-warnings: false
member-warnings: true
inherits:
  - default
ignore-paths:
  - docs
ignore-patterns:
  - __pycache__
autodetect: true
max-line-length: 120

bandit:
  run: true

dodgy:
  run: true

mccabe:
  run: true
  options:
    max-complexity: 7

pycodestyle:
  run: true
  full: true
  disable: []

pydocstyle:
  run: true
  disable:
    - D203  # 1 blank line required before class docstring: incompatible with reST and D211.
    - D205  # 1 blank line required between summary line and description: incompatible with reST.
    - D400  # First line should endd with a period: incompatible with reST.
    - D401  # First line should be in imperative mood: incompatible with the standard "Verb forms in reference documentation".

pyflakes:
  run: true
  disable:
    - F811

pylint:
  run: true

pyroma:
  run: true

mypy:
  run: true

vulture:
  run: false

frosted:
  run: false
