strictness: veryhigh
autodetect: false
inherits:
    - default
ignore-paths:
    - documentation
    - build
    - dist
ignore-patterns:
    - __pycache__
max-line-length: 120

bandit:
    run: true

dodgy:
    run: true

mccabe:
    run: true
    options:
        max-complexity: 10

pycodestyle:
    run: true
    full: true
    disable:
        - E203
          # whitespace before ':'
          # already tested by brunette
        - E402
          # Module level import not at top of file
          # already tested by pylint: wrong-import-position

pyflakes:
    run: true

pylint:
    run: true

pyroma:
    run: true

mypy:
    run: true
    options:
        ignore-missing-imports: true

vulture:
    run: false

frosted:
    run: false

pydocstyle:
    run: false
