# the configuration of the tools can be found in this file and in .prospector.yml
[tool.black]
check = true
diff = true
line-length = 120
skip-string-normalization = true
exclude = '''
(
  /(
    \.dependencies | \.custom_settings | \.venv
  )/
)
'''

[tool.isort]
line_length = 120
indent = '    '
lines_after_imports = 2
profile = "black"
skip = [".dependencies", ".custom_settings", ".venv"]

[tool.mypy]
# already tested by pylint
disable_error_code = "no-redef"

# flags
disallow_untyped_decorators = false
ignore_missing_imports = true
warn_unused_configs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
no_implicit_reexport = true
strict_equality = true

[tool.pylint.MASTER]
init-hook='import sys; sys.path.append(".")'

[tool.pylint.BASIC]
max-line-length = 120
good-names = [
    "i",
    "j",
    "pk",
    "xs",
    "ys"
]

[tool.pylint.'MESSAGES CONTROL']
disable = [
    "locally-disabled",
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring",
    "too-few-public-methods"
]
