gui:
  screenMode: half
  theme:
    selectedLineBgColor:
      - reverse
logs:
  timestamps: true
  since: ''
  tail: ''
commandTemplates:
  dockerCompose: docker compose
bulkCommands:
  services:
    - name: up
      attach: true
      shell: true
      command: '{{ .DockerCompose }} up -d --build --wait'
      serviceNames: []
    - name: down
      attach: true
      shell: true
      command: '{{ .DockerCompose }} down'
      serviceNames: []
