[colors.bright]
black = "0x808080"
blue = "0x2180DE"
cyan = "0x00ffff"
green = "0x16E616"
magenta = "0xcc00ff"
red = "0xFC4545"
white = "0xFFFFFF"
yellow = "0xfeff00"

[colors.cursor]
cursor = "0xffffff"
text = "0xF81CE5"

[colors.normal]
black = "0x000000"
blue = "0x2180DE"
cyan = "0x00ffff"
green = "0x16E616"
magenta = "0xcc00ff"
red = "0xFC4545"
white = "0xd0d0d0"
yellow = "0xfeff00"

[colors.primary]
background = "0x000000"
foreground = "0xffffff"

[font]
size = 9

[scrolling]
history = 100000

[window]
dynamic_padding = true
opacity = 0.94
